(function () {

    const produse = [

        {
            id: 1,
            name: "Set Plăcuțe Frână Brembo",
            slug: "set-placute-frana-brembo",
            category: "Frana",
            brand: "Brembo",
            sku: "MTR-FR-001",
            price: 299.99,
            oldPrice: 349.99,
            discount: 14,
            stock: 25,
            rating: 4.8,
            reviews: 124,
            popularity: 95,
            shortDescription: "Plăcuțe de frână premium Brembo, performanță maximă la orice viteză.",
            fullDescription: "Plăcuțele de frână Brembo sunt fabricate din material ceramic de înaltă calitate, oferind o putere de frânare superioară și o durată lungă de viață. Recomandate pentru șoferii care cer performanță maximă și siguranță în orice condiții de drum. Setul conține 4 plăcuțe pentru ambele roți ale aceleiași osii.",
            image: "./Assets/Product images/Set Placute Frana Brembo - 1.webp",
            gallery: ["./Assets/Product images/Set Placute Frana Brembo - 1.webp", "./Assets/Product images/Set Placute Frana Brembo - 2.webp", "./Assets/Product images/Set Placute Frana Brembo - 3.webp"],
            specifications: {
                "Brand": "Brembo",
                "Material": "Ceramic",
                "Poziție": "Față",
                "Dimensiuni": "156 × 68 × 19 mm",
                "Greutate": "1.8 kg",
                "Compatibil ABS": "Da",
                "Țara de origine": "Italia",
                "Garanție": "24 luni",
                "Cod OE": "8K0698151F",
                "Compatibilitate": "Audi / VW / Skoda"
            },
            isSale: true,
            isNew: false,
            isHot: true
        },
        {
            id: 2,
            name: "Disc Frână Față TRW",
            slug: "disc-frana-fata-trw",
            category: "Frana",
            brand: "TRW",
            sku: "MTR-FR-002",
            price: 189.99,
            oldPrice: null,
            discount: null,
            stock: 0,
            rating: 4.6,
            reviews: 89,
            popularity: 82,
            shortDescription: "Disc de frână față TRW, ventilație optimă și durabilitate ridicată.",
            fullDescription: "Discurile de frână TRW sunt proiectate pentru a oferi o frânare uniformă și sigură în orice condiții. Fabricate din fontă de calitate superioară, cu un sistem avansat de ventilație care previne supraîncălzirea și asigură o performanță constantă în trafic intens.",
            image: "./Assets/Product images/Disc Frana Fata TRW - 1.webp",
            gallery: ["./Assets/Product images/Disc Frana Fata TRW - 1.webp", "./Assets/Product images/Disc Frana Fata TRW - 2.webp", "./Assets/Product images/Disc Frana Fata TRW - 3.webp"],
            specifications: {
                "Brand": "TRW",
                "Material": "Fontă",
                "Diametru": "300 mm",
                "Grosime": "28 mm",
                "Tip": "Ventilat",
                "Poziție": "Față",
                "Greutate": "6.2 kg",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "8V0615301"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },
        {
            id: 3,
            name: "Kit Frână Spate Textar",
            slug: "kit-frana-spate-textar",
            category: "Frana",
            brand: "Textar",
            sku: "MTR-FR-003",
            price: 459.99,
            oldPrice: 529.99,
            discount: 13,
            stock: 15,
            rating: 4.7,
            reviews: 56,
            popularity: 78,
            shortDescription: "Kit complet frână spate Textar, include plăcuțe și senzori de uzură.",
            fullDescription: "Kitul complet de frână spate Textar include plăcuțe de frână, senzori de uzură și accesorii de montaj. Soluția ideală pentru o înlocuire completă a sistemului de frânare pe puntea spate, asigurând o frânare echilibrată și sigură.",
            image: "./Assets/Product images/Kit Frana Spate Textar - 1.webp",
            gallery: ["./Assets/Product images/Kit Frana Spate Textar - 1.webp", "./Assets/Product images/Kit Frana Spate Textar - 2.webp", "./Assets/Product images/Kit Frana Spate Textar - 3.webp"],
            specifications: {
                "Brand": "Textar",
                "Material": "Semi-metalic",
                "Poziție": "Spate",
                "Tip": "Kit complet",
                "Include": "Plăcuțe + Senzori + Accesorii",
                "Greutate": "2.1 kg",
                "Compatibil ABS": "Da",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "3AA698151"
            },
            isSale: true,
            isNew: false,
            isHot: false
        },
        {
            id: 4,
            name: "Lichid Frână DOT4 ATE",
            slug: "lichid-frana-dot4-ate",
            category: "Frana",
            brand: "ATE",
            sku: "MTR-FR-004",
            price: 29.99,
            oldPrice: null,
            discount: null,
            stock: 100,
            rating: 4.5,
            reviews: 210,
            popularity: 88,
            shortDescription: "Lichid de frână DOT4 ATE, punct de fierbere ridicat pentru siguranță maximă.",
            fullDescription: "Lichidul de frână ATE DOT4 este formulat pentru a rezista la temperaturi extreme și a menține performanța sistemului de frânare în cele mai dificile condiții. Testat și omologat conform standardelor internaționale.",
            image: "./Assets/Product images/Lichid Frana DOT4 ATE - 1.webp",
            gallery: ["./Assets/Product images/Lichid Frana DOT4 ATE - 1.webp", "./Assets/Product images/Lichid Frana DOT4 ATE - 2.webp"],
            specifications: {
                "Brand": "ATE",
                "Tip": "DOT4",
                "Volum": "500 ml",
                "Punct fierbere uscat": "260°C",
                "Punct fierbere umed": "165°C",
                "Vâscozitate": "750 mm²/s",
                "Standard": "ISO 4925",
                "Compatibilitate": "DOT3 / DOT4",
                "Țara de origine": "Germania",
                "Garanție": "12 luni"
            },
            isSale: false,
            isNew: true,
            isHot: false
        },

        {
            id: 5,
            name: "Bujii Iridium NGK",
            slug: "bujii-iridium-ngk",
            category: "Piese motor",
            brand: "NGK",
            sku: "MTR-PM-001",
            price: 89.99,
            oldPrice: 99.99,
            discount: 10,
            stock: 60,
            rating: 4.9,
            reviews: 178,
            popularity: 97,
            shortDescription: "Bujii cu electrod de iridium NGK, uzură redusă și aprindere perfectă.",
            fullDescription: "Bujii NGK cu electrod din iridium, oferă o aprindere mai rapidă și mai eficientă, durabilitate de până la 100.000 km și o ardere completă a combustibilului. Setul conține 4 bujii compatibile cu majoritatea motoarelor pe benzină.",
            image: "./Assets/Product images/Iridium NGKBujii Iridium NGK - 1.webp",
            gallery: ["./Assets/Product images/Iridium NGKBujii Iridium NGK - 1.webp", "./Assets/Product images/Iridium NGKBujii Iridium NGK - 2.webp", "./Assets/Product images/Iridium NGKBujii Iridium NGK - 3.webp"],
            specifications: {
                "Brand": "NGK",
                "Material electrod": "Iridium",
                "Distanță electrozi": "1.1 mm",
                "Dimensiune cheie": "16 mm",
                "Filet": "M14 x 1.25",
                "Nr. bujii": "4 buc",
                "Duritate termică": "7",
                "Țara de origine": "Japonia",
                "Garanție": "24 luni",
                "Compatibilitate": "Benzină 4T"
            },
            isSale: true,
            isNew: false,
            isHot: true
        },
        {
            id: 6,
            name: "Filtru Ulei Mann",
            slug: "filtru-ulei-mann",
            category: "Piese motor",
            brand: "Mann",
            sku: "MTR-PM-002",
            price: 24.99,
            oldPrice: null,
            discount: null,
            stock: 120,
            rating: 4.7,
            reviews: 312,
            popularity: 93,
            shortDescription: "Filtru ulei Mann, eficiență de filtrare 99.9% pentru motorul tău.",
            fullDescription: "Filtrul de ulei Mann-Filter asigură o purificare optimă a uleiului de motor, prelungind durata de viață a motorului. Realizat cu materiale filtrante de înaltă calitate și un sistem anti-drenare care previne pornirea uscată.",
            image: "./Assets/Product images/Filtru Ulei Mann - 1.webp",
            gallery: ["./Assets/Product images/Filtru Ulei Mann - 1.webp", "./Assets/Product images/Filtru Ulei Mann - 2.webp", "./Assets/Product images/Filtru Ulei Mann - 3.webp"],
            specifications: {
                "Brand": "Mann",
                "Tip": "Cartuș",
                "Eficiență": "99.9%",
                "Dimensiuni": "76 x 65 mm",
                "Filet": "M20 x 1.5",
                "Presiune by-pass": "1.5 bar",
                "Debit max": "75 L/min",
                "Țara de origine": "Germania",
                "Garanție": "12 luni",
                "Compatibilitate": "VW / BMW / Mercedes"
            },
            isSale: false,
            isNew: false,
            isHot: true
        },
        {
            id: 7,
            name: "Alternator Valeo 120A",
            slug: "alternator-valeo-120a",
            category: "Piese motor",
            brand: "Valeo",
            sku: "MTR-PM-003",
            price: 549.99,
            oldPrice: 629.99,
            discount: 13,
            stock: 10,
            rating: 4.6,
            reviews: 43,
            popularity: 72,
            shortDescription: "Alternator Valeo 120A, curent stabil pentru toți consumatorii electrici.",
            fullDescription: "Alternatorul Valeo de 120A este proiectat pentru a furniza suficient curent electric pentru toate sistemele vehiculului, inclusiv aer condiționat, faruri LED și sisteme de încălzire. Construcție robustă și fiabilitate dovedită în condiții extreme.",
            image: "./Assets/Product images/Alternator Valeo 120A - 1.webp",
            gallery: ["./Assets/Product images/Alternator Valeo 120A - 1.webp", "./Assets/Product images/Alternator Valeo 120A - 2.webp", "./Assets/Product images/Alternator Valeo 120A - 3.webp"],
            specifications: {
                "Brand": "Valeo",
                "Curent nominal": "120 A",
                "Tensiune": "12 V",
                "Putere": "1.5 kW",
                "Tip regulator": "Integrat",
                "Sens rotație": "Dreapta",
                "Nr. caneluri": "6",
                "Țara de origine": "Franța",
                "Garanție": "24 luni",
                "Cod OE": "7M3910155B"
            },
            isSale: true,
            isNew: false,
            isHot: false
        },
        {
            id: 8,
            name: "Pompă Apă Hepu",
            slug: "pompa-apa-hepu",
            category: "Piese motor",
            brand: "Hepu",
            sku: "MTR-PM-004",
            price: 229.99,
            oldPrice: null,
            discount: null,
            stock: 20,
            rating: 4.5,
            reviews: 67,
            popularity: 76,
            shortDescription: "Pompă apă Hepu, răcire optimă a motorului pentru funcționare îndelungată.",
            fullDescription: "Pompa de apă Hepu este fabricată cu materiale rezistente la coroziune și uzură, asigurând o circulație constantă a lichidului de răcire pentru a preveni supraîncălzirea motorului. Include garnituri și etanșări de calitate premium.",
            image: "./Assets/Product images/Pompa Apa Hepu - 1.webp",
            gallery: ["./Assets/Product images/Pompa Apa Hepu - 1.webp", "./Assets/Product images/Pompa Apa Hepu - 2.webp", "./Assets/Product images/Pompa Apa Hepu - 3.webp"],
            specifications: {
                "Brand": "Hepu",
                "Material": "Aluminiu",
                "Tip rotor": "Închis",
                "Diametru rotor": "80 mm",
                "Nr. paleți": "7",
                "Include garnituri": "Da",
                "Debit": "120 L/min",
                "Țara de origine": "Germania",
                "Garanție": "36 luni",
                "Cod OE": "06A121012"
            },
            isSale: false,
            isNew: true,
            isHot: false
        },

        {
            id: 9,
            name: "Amortizor Față Bilstein",
            slug: "amortizor-fata-bilstein",
            category: "Suspensie",
            brand: "Bilstein",
            sku: "MTR-SP-001",
            price: 399.99,
            oldPrice: null,
            discount: null,
            stock: 18,
            rating: 4.8,
            reviews: 94,
            popularity: 91,
            shortDescription: "Amortizor gaz Bilstein, confort și stabilitate la orice viteză.",
            fullDescription: "Amortizoarele Bilstein utilizează tehnologia cu gaz pentru a oferi o amortizare superioară și o stabilitate excelentă în viraje. Construcția monobloc garantează etanșeitate perfectă și o durată de viață îndelungată.",
            image: "./Assets/Product images/Amortizor Fata Bilstein - 1.webp",
            gallery: ["./Assets/Product images/Amortizor Fata Bilstein - 1.webp", "./Assets/Product images/Amortizor Fata Bilstein - 2.webp", "./Assets/Product images/Amortizor Fata Bilstein - 3.webp"],
            specifications: {
                "Brand": "Bilstein",
                "Tip": "Gaz",
                "Poziție": "Față",
                "Cursă": "180 mm",
                "Diametru tijă": "12 mm",
                "Forță compresie": "650 N",
                "Forță întindere": "1200 N",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "31306782672"
            },
            isSale: false,
            isNew: false,
            isHot: true
        },
        {
            id: 10,
            name: "Kit Arc Suspensie Sachs",
            slug: "kit-arc-suspensie-sachs",
            category: "Suspensie",
            brand: "Sachs",
            sku: "MTR-SP-002",
            price: 289.99,
            oldPrice: 339.99,
            discount: 15,
            stock: 12,
            rating: 4.6,
            reviews: 48,
            popularity: 74,
            shortDescription: "Arcuri suspensie Sachs, confort ridicat și manevrabilitate precisă.",
            fullDescription: "Kitul de arcuri suspensie Sachs este fabricat din oțel elastic de înaltă rezistență, tratat termic pentru durabilitate maximă. Oferă un echilibru perfect între confort și performanță, reducând balansul caroseriei în viraje.",
            image: "./Assets/Product images/Kit Arc Suspensie Sachs - 1.webp",
            gallery: ["./Assets/Product images/Kit Arc Suspensie Sachs - 1.webp", "./Assets/Product images/Kit Arc Suspensie Sachs - 2.webp", "./Assets/Product images/Kit Arc Suspensie Sachs - 3.webp"],
            specifications: {
                "Brand": "Sachs",
                "Material": "Oțel elastic",
                "Înălțime": "320 mm",
                "Diametru sârmă": "12.5 mm",
                "Diametru exterior": "150 mm",
                "Nr. spire": "8",
                "Greutate": "2.4 kg",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Poziție": "Față"
            },
            isSale: true,
            isNew: false,
            isHot: false
        },
        {
            id: 11,
            name: "Braț Suspensie Lemförder",
            slug: "brat-suspensie-lemforder",
            category: "Suspensie",
            brand: "Lemförder",
            sku: "MTR-SP-003",
            price: 199.99,
            oldPrice: null,
            discount: null,
            stock: 22,
            rating: 4.7,
            reviews: 73,
            popularity: 81,
            shortDescription: "Braț suspensie Lemförder, direcție precisă și rulare silențioasă.",
            fullDescription: "Brațul de suspensie Lemförder este fabricat din oțel forjat de înaltă rezistență și echipat cu bucșe hidraulice pentru o amortizare eficientă a vibrațiilor. Asigură o geometrie corectă a roților și o direcție precisă.",
            image: "./Assets/Product images/Brat Suspensie Lemforder - 1.webp",
            gallery: ["./Assets/Product images/Brat Suspensie Lemforder - 1.webp", "./Assets/Product images/Brat Suspensie Lemforder - 2.webp", "./Assets/Product images/Brat Suspensie Lemforder - 3.webp"],
            specifications: {
                "Brand": "Lemförder",
                "Material": "Oțel forjat",
                "Poziție": "Față stânga",
                "Include": "Bucșe + Șuruburi",
                "Lungime": "380 mm",
                "Greutate": "3.1 kg",
                "Tip bucșă": "Hidraulică",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "8K0407183A"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },

        {
            id: 12,
            name: "Filtru Aer Mann",
            slug: "filtru-aer-mann",
            category: "Filtre",
            brand: "Mann",
            sku: "MTR-FL-001",
            price: 34.99,
            oldPrice: null,
            discount: null,
            stock: 85,
            rating: 4.7,
            reviews: 156,
            popularity: 86,
            shortDescription: "Filtru aer Mann, aer curat pentru performanță optimă a motorului.",
            fullDescription: "Filtrul de aer Mann-Filter captează 99.5% din particulele de praf și impurități, asigurând un flux constant de aer curat către motor. Îmbunătățește performanța și reduce consumul de combustibil.",
            image: "./Assets/Product images/Filtru Aer Mann - 1.webp",
            gallery: ["./Assets/Product images/Filtru Aer Mann - 1.webp", "./Assets/Product images/Filtru Aer Mann - 2.webp", "./Assets/Product images/Filtru Aer Mann - 3.webp"],
            specifications: {
                "Brand": "Mann",
                "Tip": "Panou",
                "Eficiență": "99.5%",
                "Dimensiuni": "280 x 220 x 45 mm",
                "Greutate": "0.35 kg",
                "Material filtru": "Hârtie specială",
                "Interval înlocuire": "15.000 km",
                "Țara de origine": "Germania",
                "Garanție": "12 luni",
                "Cod OE": "8K0129620"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },
        {
            id: 13,
            name: "Filtru Polen Cabin Bosch",
            slug: "filtru-polen-cabin-bosch",
            category: "Filtre",
            brand: "Bosch",
            sku: "MTR-FL-002",
            price: 39.99,
            oldPrice: null,
            discount: null,
            stock: 70,
            rating: 4.6,
            reviews: 198,
            popularity: 84,
            shortDescription: "Filtru polen habitaclu Bosch, aer curat în interiorul mașinii.",
            fullDescription: "Filtrul de polen Bosch captează particule fine, polen, bacterii și mirosuri neplăcute, asigurând un aer curat și proaspăt în habitaclu. Recomandat pentru persoanele cu alergii și pentru un confort sporit la drum.",
            image: "./Assets/Product images/Filtru Polen Cabin Bosch - 1.webp",
            gallery: ["./Assets/Product images/Filtru Polen Cabin Bosch - 1.webp", "./Assets/Product images/Filtru Polen Cabin Bosch - 3.webp"],
            specifications: {
                "Brand": "Bosch",
                "Tip": "Carbon activ",
                "Eficiență": "99.8%",
                "Dimensiuni": "290 x 210 x 30 mm",
                "Greutate": "0.28 kg",
                "Strat carbon": "Da",
                "Interval înlocuire": "10.000 km",
                "Țara de origine": "Germania",
                "Garanție": "12 luni",
                "Cod OE": "8E0819439"
            },
            isSale: false,
            isNew: true,
            isHot: false
        },
        {
            id: 14,
            name: "Filtru Combustibil Mann",
            slug: "filtru-combustibil-mann",
            category: "Filtre",
            brand: "Mann",
            sku: "MTR-FL-003",
            price: 44.99,
            oldPrice: 49.99,
            discount: 10,
            stock: 55,
            rating: 4.5,
            reviews: 87,
            popularity: 79,
            shortDescription: "Filtru combustibil Mann, protecție avansată pentru sistemul de injecție.",
            fullDescription: "Filtrul de combustibil Mann separă eficient impuritățile și apa din motorină sau benzină, protejând injectoarele și pompa de combustibil. Asigură o funcționare lină și eficientă a motorului.",
            image: "./Assets/Product images/Filtru Combustibil Mann - 1.webp",
            gallery: ["./Assets/Product images/Filtru Combustibil Mann - 1.webp", "./Assets/Product images/Filtru Combustibil Mann - 2.webp", "./Assets/Product images/Filtru Combustibil Mann - 3.webp"],
            specifications: {
                "Brand": "Mann",
                "Tip": "Cartuș",
                "Presiune max": "6 bar",
                "Filtrare": "5 microni",
                "Dimensiuni": "85 x 55 mm",
                "Filet": "M16 x 1.5",
                "Debit": "60 L/h",
                "Țara de origine": "Germania",
                "Garanție": "12 luni",
                "Cod OE": "1J0201126"
            },
            isSale: true,
            isNew: false,
            isHot: false
        },

        {
            id: 15,
            name: "Far Principal LED Philips",
            slug: "far-principal-led-philips",
            category: "Iluminare",
            brand: "Philips",
            sku: "MTR-IL-001",
            price: 599.99,
            oldPrice: 699.99,
            discount: 14,
            stock: 8,
            rating: 4.9,
            reviews: 134,
            popularity: 96,
            shortDescription: "Far LED Philips, lumină puternică și vizibilitate maximă pe timp de noapte.",
            fullDescription: "Farurile LED Philips oferă o lumină albă puternică, similară luminii naturale, pentru o vizibilitate optimă în condiții de întuneric. Sistem avansat de disipare a căldurii pentru o durată de viață de până la 50.000 ore.",
            image: "./Assets/Product images/Far Principal LED Philips - 1.webp",
            gallery: ["./Assets/Product images/Far Principal LED Philips - 1.webp", "./Assets/Product images/Far Principal LED Philips - 2.webp", "./Assets/Product images/Far Principal LED Philips - 3.webp"],
            specifications: {
                "Brand": "Philips",
                "Tehnologie": "LED",
                "Temperatură": "6000K",
                "Flux luminos": "3200 lm",
                "Putere": "40W",
                "Tensiune": "12V / 24V",
                "Durată viață": "50.000 ore",
                "Omologare": "ECE R112",
                "Țara de origine": "Olanda",
                "Garanție": "36 luni"
            },
            isSale: true,
            isNew: false,
            isHot: true
        },
        {
            id: 16,
            name: "Bec Xenon Osram",
            slug: "bec-xenon-osram",
            category: "Iluminare",
            brand: "Osram",
            sku: "MTR-IL-002",
            price: 129.99,
            oldPrice: null,
            discount: null,
            stock: 35,
            rating: 4.7,
            reviews: 112,
            popularity: 83,
            shortDescription: "Bec xenon Osram, lumină intensă și fiabilitate dovedită în timp.",
            fullDescription: "Becurile xenon Osram oferă o lumină puternică, de 3 ori mai intensă decât becurile halogen standard. Durată de viață de până la 3.000 de ore și compatibilitate cu majoritatea sistemelor de iluminare auto.",
            image: "./Assets/Product images/Bec Xenon Osram - 1.webp",
            gallery: ["./Assets/Product images/Bec Xenon Osram - 1.webp", "./Assets/Product images/Bec Xenon Osram - 2.webp", "./Assets/Product images/Bec Xenon Osram - 3.webp"],
            specifications: {
                "Brand": "Osram",
                "Tehnologie": "Xenon",
                "Temperatură": "4300K",
                "Putere": "35W",
                "Flux luminos": "3200 lm",
                "Tensiune": "12V",
                "Soclu": "D1S",
                "Durată viață": "3.000 ore",
                "Țara de origine": "Germania",
                "Garanție": "24 luni"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },
        {
            id: 17,
            name: "Semnalizare LED Valeo",
            slug: "semnalizare-led-valeo",
            category: "Iluminare",
            brand: "Valeo",
            sku: "MTR-IL-003",
            price: 89.99,
            oldPrice: null,
            discount: null,
            stock: 42,
            rating: 4.5,
            reviews: 64,
            popularity: 71,
            shortDescription: "Semnalizare LED Valeo, vizibilitate crescută și design modern.",
            fullDescription: "Semnalizările LED Valeo oferă o vizibilitate excepțională în orice condiții meteorologice, cu un consum redus de energie și o durată de viață practic nelimitată. Design elegant care completează aspectul modern al mașinii.",
            image: "./Assets/Product images/Semnalizare LED Valeo - 1.webp",
            gallery: ["./Assets/Product images/Semnalizare LED Valeo - 1.webp", "./Assets/Product images/Semnalizare LED Valeo - 2.webp", "./Assets/Product images/Semnalizare LED Valeo - 3.webp"],
            specifications: {
                "Brand": "Valeo",
                "Tehnologie": "LED",
                "Culoare": "Alb / Amber",
                "Putere": "3W",
                "Tensiune": "12V",
                "Material": "Policarbonat",
                "Omologare": "ECE R6",
                "Rezistență apă": "IP67",
                "Țara de origine": "Franța",
                "Garanție": "24 luni"
            },
            isSale: false,
            isNew: true,
            isHot: false
        },

        {
            id: 18,
            name: "Kit Ambreiaj Sachs",
            slug: "kit-ambreiaj-sachs",
            category: "Transmisie",
            brand: "Sachs",
            sku: "MTR-TR-001",
            price: 799.99,
            oldPrice: 949.99,
            discount: 16,
            stock: 7,
            rating: 4.8,
            reviews: 62,
            popularity: 88,
            shortDescription: "Kit ambreiaj complet Sachs, schimbări line și fiabilitate maximă.",
            fullDescription: "Kitul de ambreiaj Sachs include disc, platou și rulment de debreiere, fabricate din materiale de înaltă calitate pentru o durată de viață îndelungată. Oferă o cuplare lină și o transmisie eficientă a puterii motorului.",
            image: "./Assets/Product images/Kit Ambreiaj Sachs - 1.webp",
            gallery: ["./Assets/Product images/Kit Ambreiaj Sachs - 1.webp", "./Assets/Product images/Kit Ambreiaj Sachs - 2.webp", "./Assets/Product images/Kit Ambreiaj Sachs - 3.webp"],
            specifications: {
                "Brand": "Sachs",
                "Tip": "Organic",
                "Diametru disc": "220 mm",
                "Nr. caneluri": "20",
                "Material disc": "Organic cu fibră",
                "Include": "Disc + Platou + Rulment",
                "Greutate": "4.5 kg",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "8D0141161E"
            },
            isSale: true,
            isNew: false,
            isHot: false
        },
        {
            id: 19,
            name: "Lichid Transmisie ATF Mobil",
            slug: "lichid-transmisie-atf-mobil",
            category: "Transmisie",
            brand: "Mobil",
            sku: "MTR-TR-002",
            price: 49.99,
            oldPrice: null,
            discount: null,
            stock: 90,
            rating: 4.6,
            reviews: 145,
            popularity: 80,
            shortDescription: "Lichid transmisie ATF Mobil, schimbări fine și protecție optimă.",
            fullDescription: "Lichidul de transmisie Mobil ATF este formulat special pentru cutii de viteze automate și manuale, oferind o lubrifiere superioară și o protecție excelentă împotriva uzurii și oxidării. Testat și aprobat de producători majori.",
            image: "./Assets/Product images/Lichid Transmisie ATF Mobil - 1.webp",
            gallery: ["./Assets/Product images/Lichid Transmisie ATF Mobil - 1.webp", "./Assets/Product images/Lichid Transmisie ATF Mobil - 2.webp"],
            specifications: {
                "Brand": "Mobil",
                "Tip": "ATF",
                "Volum": "1 L",
                "Vâscozitate": "SAE 75W-90",
                "Indice vâscozitate": "165",
                "Punct aprindere": "210°C",
                "Punct curgere": "-45°C",
                "Standard": "Dexron III",
                "Țara de origine": "SUA",
                "Garanție": "12 luni"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },
        {
            id: 20,
            name: "Senzor Viteză Roți Valeo",
            slug: "senzor-viteza-rotii-valeo",
            category: "Transmisie",
            brand: "Valeo",
            sku: "MTR-TR-003",
            price: 79.99,
            oldPrice: null,
            discount: null,
            stock: 30,
            rating: 4.4,
            reviews: 38,
            popularity: 65,
            shortDescription: "Senzor viteză roți Valeo, citire precisă pentru ABS și ESP.",
            fullDescription: "Senzorul de viteză Valeo asigură o citire exactă a turației roților, esențială pentru funcționarea corectă a sistemelor ABS, ESP și a controlului tracțiunii. Construcție robustă și rezistent la umiditate și vibrații.",
            image: "./Assets/Product images/Senzor Viteza Rotii Valeo - 1.webp",
            gallery: ["./Assets/Product images/Senzor Viteza Rotii Valeo - 1.webp", "./Assets/Product images/Senzor Viteza Rotii Valeo - 2.webp", "./Assets/Product images/Senzor Viteza Rotii Valeo - 3.webp"],
            specifications: {
                "Brand": "Valeo",
                "Tip": "Inductiv",
                "Lungime cablu": "65 cm",
                "Poziție": "Față spate",
                "Rezistență": "850 Ω",
                "Conector": "2 pini",
                "Tensiune": "5V / 12V",
                "Țara de origine": "Franța",
                "Garanție": "24 luni",
                "Cod OE": "1J0927807"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },

        {
            id: 21,
            name: "Bieletă Direcție TRW",
            slug: "bieleta-directie-trw",
            category: "Directie",
            brand: "TRW",
            sku: "MTR-DR-001",
            price: 119.99,
            oldPrice: null,
            discount: null,
            stock: 28,
            rating: 4.6,
            reviews: 55,
            popularity: 73,
            shortDescription: "Bieletă direcție TRW, direcție precisă și uzură redusă a anvelopelor.",
            fullDescription: "Bieleta de direcție TRW este fabricată din oțel călit și tratat termic, cu rosturi sferice de înaltă precizie care asigură o mișcare lină și fără jocuri. Îmbunătățește stabilitatea direcției și prelungește durata de viață a anvelopelor.",
            image: "./Assets/Product images/Bieleta Directie TRW - 1.webp",
            gallery: ["./Assets/Product images/Bieleta Directie TRW - 1.webp", "./Assets/Product images/Bieleta Directie TRW - 3.webp"],
            specifications: {
                "Brand": "TRW",
                "Material": "Oțel călit",
                "Poziție": "Față stânga",
                "Filet interior": "M14 x 1.5",
                "Filet exterior": "M12 x 1.5",
                "Lungime": "285 mm",
                "Greutate": "0.65 kg",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "8E0419803"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },
        {
            id: 22,
            name: "Cremalieră Direcție ZF",
            slug: "cremaliera-directie-zf",
            category: "Directie",
            brand: "ZF",
            sku: "MTR-DR-002",
            price: 1499.99,
            oldPrice: 1699.99,
            discount: 12,
            stock: 4,
            rating: 4.9,
            reviews: 29,
            popularity: 85,
            shortDescription: "Cremalieră direcție ZF, precizie chirurgicală și răspuns imediat.",
            fullDescription: "Cremaliera de direcție ZF oferă un răspuns rapid și precis la comenzile volanului, cu un sistem hidraulic sau electric integrat. Fabricată cu toleranțe microscopice pentru o durată de viață excepțională și un confort sporit la volan.",
            image: "./Assets/Product images/Cremaliera Directie ZF - 1.webp",
            gallery: ["./Assets/Product images/Cremaliera Directie ZF - 1.webp", "./Assets/Product images/Cremaliera Directie ZF - 2.webp", "./Assets/Product images/Cremaliera Directie ZF - 3.webp"],
            specifications: {
                "Brand": "ZF",
                "Tip": "Hidraulic",
                "Raport": "16:1",
                "Nr. rotații": "3.2",
                "Lungime": "1250 mm",
                "Diametru tijă": "22 mm",
                "Greutate": "8.5 kg",
                "Țara de origine": "Germania",
                "Garanție": "36 luni",
                "Cod OE": "8E1423055A"
            },
            isSale: true,
            isNew: false,
            isHot: true
        },
        {
            id: 23,
            name: "Pompă Servodirecție Valeo",
            slug: "pompa-servodirectie-valeo",
            category: "Directie",
            brand: "Valeo",
            sku: "MTR-DR-003",
            price: 649.99,
            oldPrice: null,
            discount: null,
            stock: 9,
            rating: 4.7,
            reviews: 41,
            popularity: 77,
            shortDescription: "Pompă servodirecție Valeo, asistență la direcție lină și silențioasă.",
            fullDescription: "Pompa de servodirecție Valeo asigură presiunea optimă pentru un sistem de direcție asistat, oferind o manevrare ușoară și precisă. Construcția compactă și etanșările de calitate previn pierderile de lichid.",
            image: "./Assets/Product images/Pompa Servodirectie Valeo - 1.webp",
            gallery: ["./Assets/Product images/Pompa Servodirectie Valeo - 1.webp", "./Assets/Product images/Pompa Servodirectie Valeo - 2.webp", "./Assets/Product images/Pompa Servodirectie Valeo - 3.webp"],
            specifications: {
                "Brand": "Valeo",
                "Debit": "8 L/min",
                "Presiune": "110 bar",
                "Turație max": "6000 rpm",
                "Tip": "Paletă",
                "Volum rezervor": "0.4 L",
                "Sens rotație": "Dreapta",
                "Țara de origine": "Franța",
                "Garanție": "24 luni",
                "Cod OE": "8E0145155"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },

        {
            id: 24,
            name: "Tampon Evacuare Meyle",
            slug: "tampon-evacuare-meyle",
            category: "Evacuare",
            brand: "Meyle",
            sku: "MTR-EV-001",
            price: 49.99,
            oldPrice: null,
            discount: null,
            stock: 45,
            rating: 4.5,
            reviews: 83,
            popularity: 70,
            shortDescription: "Tampon evacuare Meyle, amortizare eficientă și montaj facil.",
            fullDescription: "Tamponul de evacuare Meyle este fabricat din cauciuc de înaltă calitate, cu inserții metalice pentru o fixare sigură. Reduce vibrațiile sistemului de evacuare și previne transmiterea zgomotelor în habitaclu.",
            image: "./Assets/Product images/Tampon Evacuare Meyle - 1.webp",
            gallery: ["./Assets/Product images/Tampon Evacuare Meyle - 1.webp", "./Assets/Product images/Tampon Evacuare Meyle - 2.webp", "./Assets/Product images/Tampon Evacuare Meyle - 3.webp"],
            specifications: {
                "Brand": "Meyle",
                "Material": "Cauciuc + Metal",
                "Duritate": "65 Shore",
                "Poziție": "Intermediar",
                "Diametru gaură": "10 mm",
                "Greutate": "0.35 kg",
                "Rezistență termică": "-30°C / +120°C",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "8E0253155"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },
        {
            id: 25,
            name: "Sondă Lambda Bosch",
            slug: "sonda-lambda-bosch",
            category: "Evacuare",
            brand: "Bosch",
            sku: "MTR-EV-002",
            price: 139.99,
            oldPrice: 159.99,
            discount: 13,
            stock: 22,
            rating: 4.7,
            reviews: 96,
            popularity: 82,
            shortDescription: "Sondă Lambda Bosch, emisii reduse și consum optimizat de combustibil.",
            fullDescription: "Sonda Lambda Bosch măsoară conținutul de oxigen din gazele de evacuare și ajustează amestecul aer-combustibil pentru o ardere eficientă. Contribuie la reducerea emisiilor poluante și la optimizarea consumului.",
            image: "./Assets/Product images/Sonda Lambda Bosch - 1.webp",
            gallery: ["./Assets/Product images/Sonda Lambda Bosch - 1.webp", "./Assets/Product images/Sonda Lambda Bosch - 2.webp", "./Assets/Product images/Sonda Lambda Bosch - 3.webp"],
            specifications: {
                "Brand": "Bosch",
                "Tip": "Bandă largă",
                "Nr. fire": "4",
                "Lungime cablu": "50 cm",
                "Filet": "M18 x 1.5",
                "Tensiune": "12V",
                "Semnal": "0.1 - 0.9V",
                "Țara de origine": "Germania",
                "Garanție": "24 luni",
                "Cod OE": "0258017125"
            },
            isSale: true,
            isNew: false,
            isHot: false
        },
        {
            id: 26,
            name: "Catalizator Universal Bosal",
            slug: "catalizator-universal-bosal",
            category: "Evacuare",
            brand: "Bosal",
            sku: "MTR-EV-003",
            price: 349.99,
            oldPrice: null,
            discount: null,
            stock: 6,
            rating: 4.4,
            reviews: 33,
            popularity: 62,
            shortDescription: "Catalizator universal Bosal, emisii reduse și performanță constantă.",
            fullDescription: "Catalizatorul universal Bosal reduce emisiile nocive prin conversia gazelor toxice în compuși inofensivi. Compatibil cu majoritatea sistemelor de evacuare standard și omologat conform normelor europene de poluare.",
            image: "./Assets/Product images/Catalizator Universal Bosal - 1.webp",
            gallery: ["./Assets/Product images/Catalizator Universal Bosal - 1.webp", "./Assets/Product images/Catalizator Universal Bosal - 2.webp", "./Assets/Product images/Catalizator Universal Bosal - 3.webp"],
            specifications: {
                "Brand": "Bosal",
                "Material": "Metalic ceramic",
                "Diametru intrare": "50 mm",
                "Diametru ieșire": "50 mm",
                "Lungime": "180 mm",
                "Omologare": "Euro 5",
                "Tip": "Universal",
                "Țara de origine": "Belgia",
                "Garanție": "24 luni",
                "Cod OE": "099108"
            },
            isSale: false,
            isNew: true,
            isHot: false
        },

        {
            id: 27,
            name: "Set Chei Bușoane 17 buc",
            slug: "set-chei-busoane-17-buc",
            category: "Accesorii Auto",
            brand: "Teng Tools",
            sku: "MTR-AC-001",
            price: 49.99,
            oldPrice: 59.99,
            discount: 17,
            stock: 35,
            rating: 4.6,
            reviews: 201,
            popularity: 89,
            shortDescription: "Set chei bușoane 17 bucăți, oțel crom-vanadiu, carcasă organizată.",
            fullDescription: "Setul de chei bușoane Teng Tools conține 17 bucăți de la 6 la 22 mm, fabricate din oțel crom-vanadiu tratat termic. Includ o carcasă organizatoare pentru depozitare ușoară și transport. Ideale pentru uz casnic și profesional.",
            image: "./Assets/Product images/Set Chei Busoane 17 buc - 1.webp",
            gallery: ["./Assets/Product images/Set Chei Busoane 17 buc - 1.webp", "./Assets/Product images/Set Chei Busoane 17 buc - 2.webp"],
            specifications: {
                "Brand": "Teng Tools",
                "Material": "Oțel Cr-V",
                "Nr. bucăți": "17",
                "Dimensiuni": "6 - 22 mm",
                "Profil": "6 colțuri",
                "Carcasă": "Inclusă",
                "Tratament": "Fosfatare neagră",
                "Țara de origine": "Taiwan",
                "Garanție": "60 luni",
                "Standard": "DIN 3120"
            },
            isSale: true,
            isNew: false,
            isHot: false
        },
        {
            id: 28,
            name: "Suport Telefon Universal",
            slug: "suport-telefon-universal",
            category: "Accesorii Auto",
            brand: "Generic",
            sku: "MTR-AC-002",
            price: 19.99,
            oldPrice: null,
            discount: null,
            stock: 150,
            rating: 4.3,
            reviews: 420,
            popularity: 92,
            shortDescription: "Suport telefon universal pentru bord, prindere sigură și reglabilă.",
            fullDescription: "Suportul universal pentru telefon se montează ușor pe bord sau parbriz, cu un braț flexibil care permite reglarea unghiului de vizualizare. Compatibil cu telefoane de până la 6.7 inci și se instalează fără unelte.",
            image: "./Assets/Product images/Suport Telefon Universal - 1.webp",
            gallery: ["./Assets/Product images/Suport Telefon Universal - 1.webp","./Assets/Product images/Suport Telefon Universal - 3.webp"],
            specifications: {
                "Brand": "Generic",
                "Tip": "Bord / Parbriz",
                "Dimensiune max": "6.7 inci",
                "Material": "Plastic ABS",
                "Prindere": "Vacuum + Clește",
                "Rotire": "360°",
                "Culoare": "Negru",
                "Țara de origine": "China",
                "Garanție": "12 luni",
                "Compatibilitate": "Android / iOS"
            },
            isSale: false,
            isNew: false,
            isHot: true
        },
        {
            id: 29,
            name: "Set Prosoape Microfibră 5 buc",
            slug: "set-prosoape-microfibra-5-buc",
            category: "Accesorii Auto",
            brand: "Generic",
            sku: "MTR-AC-003",
            price: 14.99,
            oldPrice: null,
            discount: null,
            stock: 200,
            rating: 4.4,
            reviews: 315,
            popularity: 87,
            shortDescription: "Set prosoape microfibră 5 buc, fără zgârieturi și absorbție maximă.",
            fullDescription: "Prosoapele din microfibră sunt esențiale pentru curățarea mașinii fără a zgâria vopseaua. Absorb de 7 ori mai multă apă decât prosoapele obișnuite și pot fi spălate și refolosite de sute de ori. Setul conține 5 prosoape de dimensiuni diferite.",
            image: "./Assets/Product images/Set Prosoape Microfibra 5 buc - 1.webp",
            gallery: ["./Assets/Product images/Set Prosoape Microfibra 5 buc - 1.webp", "./Assets/Product images/Set Prosoape Microfibra 5 buc - 2.webp"],
            specifications: {
                "Brand": "Generic",
                "Material": "Microfibră",
                "Nr. bucăți": "5",
                "Dimensiuni": "40x40 / 30x30 / 20x20 cm",
                "Gramaj": "300 g/m²",
                "Culoare": "Albastru",
                "Refolosibil": "Da (spălabil)",
                "Țara de origine": "China",
                "Garanție": "6 luni",
                "Utilizare": "Caroserie / Geamuri / Interior"
            },
            isSale: false,
            isNew: false,
            isHot: false
        },
        {
            id: 30,
            name: "Organizator Portbagaj",
            slug: "organizator-portbagaj",
            category: "Accesorii Auto",
            brand: "Generic",
            sku: "MTR-AC-004",
            price: 39.99,
            oldPrice: null,
            discount: null,
            stock: 60,
            rating: 4.5,
            reviews: 178,
            popularity: 85,
            shortDescription: "Organizator portbagaj pliabil, compartimente multiple și material rezistent.",
            fullDescription: "Organizatorul de portbagaj menține ordinea în mașină, cu compartimente pentru cumpărături, unelte, cabluri și alte obiecte. Realizat din material textil rezistent, cu bază antiderapantă și mânere pentru transport ușor.",
            image: "./Assets/Product images/Organizator Portbagaj - 1.webp",
            gallery: ["./Assets/Product images/Organizator Portbagaj - 1.webp", "./Assets/Product images/Organizator Portbagaj - 2.webp", "./Assets/Product images/Organizator Portbagaj - 3.webp"],
            specifications: {
                "Brand": "Generic",
                "Material": "Poliester 600D",
                "Dimensiuni": "60 x 35 x 25 cm",
                "Compartimente": "5",
                "Pliabil": "Da",
                "Bază antiderapantă": "Da",
                "Mânere": "Da",
                "Culoare": "Negru / Gri",
                "Țara de origine": "China",
                "Garanție": "12 luni"
            },
            isSale: false,
            isNew: true,
            isHot: false
        }
    ];

    localStorage.setItem("motrix_products", JSON.stringify(produse));
    console.log("Produsele au fost salvate în localStorage.");
})();
